name: Deploy to Google Play
permissions:
  contents: read

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    environment: main

    steps:
      - uses: actions/checkout@v4
      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Set up auth config
        env:
          AUTH_CONFIG: ${{secrets.AUTH_CONFIG}}
        run:
          echo "$AUTH_CONFIG" > app/src/main/res/raw/auth_config_apk.json
      - name: Decode keystore
        env:
          KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
          STRORE_FILE: ${{secrets.STRORE_FILE}}
        run: echo "$KEYSTORE_BASE64" | base64 --decode > app/key.jks
      - name: Set up keystore Debug
        env:
            KEY_ALIAS: ${{secrets.KEY_ALIAS}}
            KEY_PASSWORD: ${{secrets.KEY_PASSWORD}}
            STORE_PASSWORD: ${{secrets.STORE_PASSWORD}}
        run: |
            echo "keyAlias=$KEY_ALIAS" > keystore.properties
            echo "keyPassword=$KEY_PASSWORD" >> keystore.properties
            echo "storePassword=$STORE_PASSWORD" >> keystore.properties
            echo "storeFile=key.jks" >> keystore.properties
      - name: Set up keystore Release
        env:
          KEY_ALIAS: ${{secrets.KEY_ALIAS}}
          KEY_PASSWORD: ${{secrets.KEY_PASSWORD}}
          STORE_PASSWORD: ${{secrets.STORE_PASSWORD}}
        run: |
          echo "keyAlias=$KEY_ALIAS" > keystore.properties.release
          echo "keyPassword=$KEY_PASSWORD" >> keystore.properties.release
          echo "storePassword=$STORE_PASSWORD" >> keystore.properties.release
          echo "storeFile=key.jks" >> keystore.properties.release
      - name: Set up env
        env:
            MSAL_HOST: ${{secrets.MSAL_HOST}}
            MSAL_PATH: ${{secrets.MSAL_PATH}}
        run: |
            echo "sdk.dir=$ANDROID_HOME" > local.properties
            echo "MSAL_HOST=$MSAL_HOST" >> local.properties
            echo "MSAL_PATH=$MSAL_PATH" >> local.properties
      - name: Version Bump
        uses: chkfung/android-version-actions@v1.2.3
        with:
          gradlePath: app/build.gradle.kts
          versionCode: ${{ github.run_number }}
      - name: Build Bindle
        run: ./gradlew bundleRelease
      - name: Upload AAB
        uses: actions/upload-artifact@v4
        with:
          name: release-aab
          path: app/build/outputs/bundle/release/app-release.aab

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment: main
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - uses: 'actions/checkout@v4'

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: release-aab
          path: release/

      - id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.SERVICE_ACCOUNT }}

      - name: Upload to Google Play
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJson: ${{ steps.auth.outputs.credentials_file_path }}
          packageName: anchovy.team.epialarm
          releaseFiles: app/build/outputs/bundle/release/app-release.aab
          track: internal
